### ISSUE TITLE
[BUG]esteem v2.1.0 The app got completely crashed, while I tried to reopen the large size blog 

### ISSUE THREAD

**Issue by peerzadaaabid** [ecency/ecency-mobile#930]
#### Project Information
Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

#### Expected behaviour
The app should have not been crashed,while reopening of long blog.

#### Actual behaviour
Here while going through the blog whose size is large,I tried to open it and eventually it opened.However when I tried to reopen it again the app got crashed.

1-Download the application
2- Go to the long blog/post
3- Open it and scroll down 
4-Go back to blog
5- Open it and notice the error

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: Note 4

Recording Of The Bug
https://youtu.be/jIfFrUgCERg

My Github Account

https://github.com/peerzadaaabid

Logcat

`java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1407752 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3812)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6237)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: android.os.TransactionTooLargeException: data parcel size 1407752 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:618)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3664)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3804)`

**Comment by mistikk** [comment]
@peerzadaaabid can you check with v2.2. I am testing with same post, it didnt crash just loading slowly, we are working for slow loading
